/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  overviewSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        'overview/introduction',
        'overview/overview',
        'overview/key-features',
        'overview/disclaimer'
      ],
    },
  ],
  learnSidebar: [
    'learn/overview',
    {
      type: 'category',
      label: 'Basics',
      items: [
        'learn/computor', 
        'learn/spectrum',
        'learn/quorum',
        'learn/cryptography',
      ],
    },
    {
      type: 'category',
      label: 'Mining',
      items: [
        'learn/pouw',
        'learn/hw',
        'learn/sw',
        'learn/pool',
      ],
    },
    {
      type: 'category',
      label: 'How to buy',
      items: [
        'learn/exchanges',
        'learn/wallets',

      ],
    },
    'learn/use-cases',
    {
      type: 'category',
      label: 'Roadmap',
      items: [
        'learn/milestones',
        'learn/features',
        'learn/releases',
      ],
    },
    'learn/glossary',
  ],
  
  compSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'computors/prerequisites',
        'computors/installation',
        'computors/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Run a Computor',
      items: [
        'computors/bm',
        'computors/vm',
      ],
    },
    {
      type: 'category',
      label: 'Monitoring & Maintenance',
      items: [
        'computors/logging',
        'computors/backup-restore',
        'computors/upgrading',
      ],
    },
  ],
  devSidebar: [
    'developers/intro',
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'developers/environment',
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'Core API',
      items: [
        'api/blocks',
        'api/transactions',
      ],
    },
  ],
};

module.exports = sidebars;
